# cPanel Git deployment config
# Deploy the production build from ./dist
# (Build locally with: npm run build)
deployment:
  tasks:
    # Use the account home directory so this works even if the server uses /home, /home1, etc.
    - export DEPLOYPATH="${HOME}/public_html/"
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rm -rf "$DEPLOYPATH"/*
    - /bin/cp -a ./dist/. "$DEPLOYPATH"
